### ISSUE TITLE
Payment Proof for iOS

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/ios-wallet#58] opened 2019-03-24 08:43 UTC
Design is needed for iOS

**Comment by alexandrashelenkova** [comment] 2019-03-26 08:24
@kaminskyelina can you tell me please in which project that issue is? How urgent is it?

**Comment by alexandrashelenkova** [comment] 2019-04-01 10:58
Duplicate of that task https://github.com/BeamMW/ios-wallet/issues/63

**Comment by Denis-Asipenko** [comment] 2019-04-02 12:53
Design implemented
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ca198c89f489505ca286c93
![image](https://user-images.githubusercontent.com/45556620/55403764-34f16480-555f-11e9-8282-1e13d40f3e1a.png)
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ca198c8e249f005dc8434d2
![image](https://user-images.githubusercontent.com/45556620/55403794-49356180-555f-11e9-9948-dd0c8a43ad33.png)
https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5ca198c911b19f79560e97f6
![image](https://user-images.githubusercontent.com/45556620/55403842-610ce580-555f-11e9-9d5b-e6b2c88331d8.png)

**Closed by Denis-Asipenko** 2019-04-02 12:53 UTC
Labels: design, task
